# Generated by Django 3.2.4 on 2021-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211202_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='body',
            field=models.TextField(default={}, max_length=4096),
            preserve_default=False,
        ),
    ]
