# Generated by Django 3.2.4 on 2021-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='body',
            field=models.JSONField(max_length=4096, null=True),
        ),
    ]
