# Generated by Django 3.2.4 on 2021-12-22 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('movies', '0008_comment'), ('movies', '0009_comment_movie_id'), ('movies', '0010_alter_comment_owner'), ('movies', '0011_alter_comment_owner'), ('movies', '0012_remove_comment_movie_id'), ('movies', '0013_auto_20211217_1815'), ('movies', '0014_alter_moviecomment_owner'), ('movies', '0015_auto_20211222_1344'), ('movies', '0016_remove_moviecomment_owner'), ('movies', '0017_auto_20211222_1424'), ('movies', '0018_auto_20211222_1429')]

    dependencies = [
        ('movies', '0007_alter_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=2000)),
                ('movie_id', models.IntegerField(default=None)),
                ('created_date', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
