# Generated by Django 3.2.4 on 2021-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_comment_squashed_0018_auto_20211222_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
